# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-11-04 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=7)),
                ('team', models.CharField(max_length=11)),
                ('priority', models.CharField(max_length=9)),
            ],
        ),
    ]
